sudo: required
language: bash
before_install:
  - scripts/travis-installer
script:
  - make kubepress
after_failure:
  - cat terraform/terraform.tfstate
after_success:
  - cat terraform/terraform.tfstate
  
