sudo: required
language: bash
before_install:
  - scripts/travis-installer
script:
  - make kubepress
addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - ./terraform/terraform.tfstate
      - $HOME/.kube/config
